### ISSUE TITLE
KeyError: 'zones'

### ISSUE THREAD

**Issue by gibson9583** [MizterB/homeassistant-infinitude#21]
Getting the following error in startup. I have configured with an IP / port in the configuration.yaml.

If i go to http://my-ip:3005/api/config - a valid response is returned. I only have 1 zone. I see a previous comment with this error has been closed, but the suggestion does not seem to fit here.

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 79, in setup_platform
    zones = status["zones"][0]["zone"]
KeyError: 'zones'`

**Comment by MizterB** [comment]
Can you please share the output of http://my-ip:3005/api/status ?  The zones are pulled from the status call.

**Comment by gibson9583** [comment]
Hmm...This returns empty:

{"data":{},"status":"success"}

However, in infinitude I can see zones:
![image](https://user-images.githubusercontent.com/725259/83789369-9c73da00-a664-11ea-942d-1c2ca7addab6.png)

**Comment by cgibsonwellogic** [comment]
Ok found the issue. I should not have pulled from DockerHub. The version was too old.

Now on startup:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 90, in setup_platform
    devices.append(InfinitudeZone(infinitude, zones[i]["id"], zone_name))
  File "/config/custom_components/infinitude/climate.py", line 183, in __init__
    self.update()
  File "/config/custom_components/infinitude/climate.py", line 293, in update
    dt = datetime.datetime.strptime(get_safe(self.system_status, "localTime"),"%Y-%m-%dT%H:%M:%S")
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: -05:00`

**Comment by gibson9583** [comment]
Ok - found the issue. It was due to pulling the image from docker hub... That image was old so I  built it from scratch from the infinitude repo. Now works as expected!
