### ISSUE TITLE
Cannot connect 

### ISSUE THREAD

**Issue by lukazareba** [MizterB/homeassistant-infinitude#43]
Hi, I have no idea how to connect. I use standard configuration of yaml file.

What could be the problem?

Logger: homeassistant.components.climate
Source: custom_components/infinitude/climate.py:278
Integration: Klimat (documentation, issues)
First occurred: 09:07:41 (1 occurrences)
Last logged: 09:07:41

Error while setting up infinitude platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 122, in setup_platform
    devices.append(InfinitudeZone(infinitude, zones[i]["id"], zone_name))
  File "/config/custom_components/infinitude/climate.py", line 216, in __init__
    self.update()
  File "/config/custom_components/infinitude/climate.py", line 278, in update
    self._current_temperature = float(get_safe(self.zone_status, "rt"))
TypeError: float() argument must be a string or a real number, not 'NoneType'

**Comment by MizterB** [comment]
Use https://github.com/MizterB/homeassistant-infinitude-beyond to connect the the Home Assistant UI, rather than YAML.
