### ISSUE TITLE
Zone Errors

### ISSUE THREAD

**Issue by Bchap9** [MizterB/homeassistant-infinitude#9]
When trying to load HA at first, I get an error:
`Error while setting up platform infinitude
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/infinitude/climate.py", line 69, in setup_platform
    devices.append(InfinitudeZone(infinitude, zone["id"]))
  File "/config/custom_components/infinitude/climate.py", line 111, in __init__
    self.update()
  File "/config/custom_components/infinitude/climate.py", line 134, in update
    self._occupancy = self._zoneStatus["occupancy"][0]                    # occupied, unoccupied, motion
KeyError: 'occupancy'`

Haven't been able to get this to work yet, in my environment I only have 1 zone, and from reading some other errors, it seems to be coded for multiple zones.

Any help is greatly appreciated

**Comment by sytchi** [comment]
Does your termostat have an occupancy sensor?

**Comment by MizterB** [comment]
This was fixed in the latest release.
